### ISSUE TITLE
SyntaxError: Invalid shorthand property initializer

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/BlockChain#13]
C:\Users\minji\Code\201810808\src\OrderEventUse.js:17
            filter: {_from: accounts[0],_value=d},
                                        ^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by minji-o-j** [comment]
초기변수 =가아니라 :으로
filter: {_from: accounts[0],**_value:d},**
