### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connection not open on send()

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/BlockChain#14]
(node:37016) UnhandledPromiseRejectionWarning: Error: connection not open on send()
    at Object.ConnectionError (C:\Users\minji\Code\201810808\node_modules\web3-core-helpers\src\errors.js:69:23)
    at Object.ConnectionNotOpenError (C:\Users\minji\Code\201810808\node_modules\web3-core-helpers\src\errors.js:48:21)
    at C:\Users\minji\Code\201810808\node_modules\web3-providers-ws\src\index.js:181:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider._onClose (C:\Users\minji\Code\201810808\node_modules\web3-providers-ws\src\index.js:180:27)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\minji\Code\201810808\node_modules\yaeti\lib\EventTarget.js:115:12)
    at W3CWebSocket.onConnectFailed (C:\Users\minji\Code\201810808\node_modules\@web3-js\websocket\lib\W3CWebSocket.js:219:14)
    at WebSocketClient.<anonymous> (C:\Users\minji\Code\201810808\node_modules\@web3-js\websocket\lib\W3CWebSocket.js:59:25)
    at WebSocketClient.emit (events.js:310:20)
    at WebSocketClient.failHandshake (C:\Users\minji\Code\201810808\node_modules\@web3-js\websocket\lib\WebSocketClient.js:339:10)
    at ClientRequest.<anonymous> (C:\Users\minji\Code\201810808\node_modules\@web3-js\websocket\lib\WebSocketClient.js:278:18)
    at ClientRequest.emit (events.js:310:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:476:22)
    at Socket.emit (events.js:310:20)
(node:37016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by minji-o-j** [comment]
_gethNow.bat에서 
--ws --wsaddr="localhost" --wsport "8446"  **--wsorigins="*"** <<굵은글씨 부분 추가
- 반드시 "*" <<(쌍따옴표)로 해야함  
- ('*'으로 해서 생겼었음)
