### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: The contract code couldn't be stored, please check your gas limit.

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/BlockChain#5]
(node:34588) UnhandledPromiseRejectionWarning: Error: The contract code couldn't be stored, please check your gas limit.
    at Object.TransactionError (C:\Users\minji\Code\201810808\node_modules\web3-core-helpers\src\errors.js:93:21)
    at Object.ContractCodeNotStoredError (C:\Users\minji\Code\201810808\node_modules\web3-core-helpers\src\errors.js:102:21)
    at C:\Users\minji\Code\201810808\node_modules\web3-core-method\src\index.js:394:40
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:34588) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:34588) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by minji-o-j** [comment]
"gas: 2000000" the solution.
가스를 크게하니 해결
