### ISSUE TITLE
myBank.methods.getBalance(...).call.then is not a function

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/BlockChain#6]
myBank.methods.getBalance().call.then(console.log);
                                 ^

TypeError: myBank.methods.getBalance(...).call.then is not a function
    at Object.<anonymous> (C:\Users\minji\Code\201810808\src\BankUse.js:5:34)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by minji-o-j** [comment]
myBank.methods.getBalance().call().then(function(value) {console.log(value);});
로수정
