### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""     at Object.InvalidResponse

### ISSUE THREAD

**Issue by minji-o-j** [minji-o-j/BlockChain#9]
(node:37468) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (C:\Users\minji\Code\201810808\node_modules\web3-core-helpers\src\errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (C:\Users\minji\Code\201810808\node_modules\web3-providers-http\src\index.js:106:32)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\minji\Code\201810808\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (C:\Users\minji\Code\201810808\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpRequestError (C:\Users\minji\Code\201810808\node_modules\xhr2-cookies\dist\xml-http-request.js:349:14)
    at ClientRequest.<anonymous> (C:\Users\minji\Code\201810808\node_modules\xhr2-cookies\dist\xml-http-request.js:252:61)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:37468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37468) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by minji-o-j** [comment]
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:8345")); 제대로 썼는지 확인

**Comment by minji-o-j** [comment]
마이닝을 중간에 끊어버렸을때(하다가 중단)할 때도 발생함
